Update buil-push.yml

diff --git a/.github/workflows/buil-push.yml b/.github/workflows/buil-push.yml
--- a/.github/workflows/buil-push.yml
+++ b/.github/workflows/buil-push.yml
@@ -47,6 +47,9 @@ jobs:
           script: |
             echo "Changing to deployment directory..."
             cd ~/Infin8-Deployment || { echo "Deployment directory not found"; exit 1; }
+            cd ~/Infin8 || { echo "Infin8 directory not found"; exit 1; }
+            echo "Pulling latest code..."
+            git pull origin main
             echo "Stopping existing containers..."
             sudo docker-compose down
             echo "Pulling latest images..."
